package extra;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import program.modell.Kartya;

public class KartyaEpito extends javax.swing.JFrame {

    private ArrayList<Kartya> kartyak;
    private File file;

    public KartyaEpito() {
        initComponents();
        kartyak = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaValasz = new javax.swing.JTextArea();
        txtKerdes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnKovetkezoKartya = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCsomagMentese = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Csomag készítő");

        jLabel1.setText("Kérdés:");

        txaValasz.setColumns(20);
        txaValasz.setRows(5);
        jScrollPane1.setViewportView(txaValasz);

        jLabel2.setText("Válasz:");

        btnKovetkezoKartya.setText("Következő kártya");
        btnKovetkezoKartya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKovetkezoKartyaActionPerformed(evt);
            }
        });

        jMenu1.setText("Program");

        mnuCsomagMentese.setText("Csomag mentése...");
        mnuCsomagMentese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCsomagMenteseActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCsomagMentese);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1)
                    .addComponent(btnKovetkezoKartya))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(356, 356, 356))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtKerdes)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKovetkezoKartya)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCsomagMenteseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCsomagMenteseActionPerformed
        int g;
        if (!txtKerdes.getText().isBlank()) {
            String uzenet = "Az utolsó kártya nincs a csomaghoz adva, folytatja a mentést?";
            g = JOptionPane.showConfirmDialog(rootPane, uzenet, "Biztos menti?", JOptionPane.YES_NO_OPTION);
        }else{
            g = JOptionPane.OK_OPTION;
        }
        if (g == JOptionPane.OK_OPTION) {
            JFileChooser dlgMent = new JFileChooser();
            FileFilter filter = new FileNameExtensionFilter("kcs", "*.kcs kártya csomag");
            dlgMent.addChoosableFileFilter(filter);
            dlgMent.setFileFilter(filter);
            dlgMent.showSaveDialog(rootPane);
            file = dlgMent.getSelectedFile();
            String fn = file.getPath() + "." + dlgMent.getFileFilter().getDescription();
            fajlMentese(fn);
        }
    }//GEN-LAST:event_mnuCsomagMenteseActionPerformed

    private void btnKovetkezoKartyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKovetkezoKartyaActionPerformed
        kartyatKeszit();
        uresKartya();
    }//GEN-LAST:event_btnKovetkezoKartyaActionPerformed

    private void fajlMentese(String fp) {
        String kimenet = "";
        for (Kartya kartya : kartyak) {
            kimenet += kartya.getKerdes();
            kimenet += "/";
            kimenet += kartya.getValasz();
            kimenet += "\n";
        }
        try {
            Files.write(Paths.get(fp), kimenet.getBytes());
        } catch (IOException ex) {
            Logger.getLogger(KartyaEpito.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void kartyatKeszit() {
        String kerdes = txtKerdes.getText();
        String valasz = txaValasz.getText();
        Kartya k = new Kartya(kerdes, valasz);
        kartyak.add(k);
    }

    private void uresKartya() {
        txtKerdes.setText("");
        txaValasz.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KartyaEpito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KartyaEpito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KartyaEpito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KartyaEpito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KartyaEpito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKovetkezoKartya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuCsomagMentese;
    private javax.swing.JTextArea txaValasz;
    private javax.swing.JTextField txtKerdes;
    // End of variables declaration//GEN-END:variables

}
